### PR TITLE
Apply clj-kondo suggestions

### PR DESCRIPTION
**Pull request by evg-tso**
Changes:
- Apply [clj-kondo](https://github.com/clj-kondo/clj-kondo) suggestions

### CODE REVIEW

**Comment by weavejester** [comment]
Can you keep the spelling correction, and remove everything else?

**Comment by evg-tso** [comment]
> Can you keep the spelling correction, and remove everything else?

Sure.  
Can you elaborate on keeping `if-let` without an `else` branch?

**Comment by weavejester** [comment]
> Can you elaborate on keeping `if-let` without an `else` branch?

`(when-let [x y] z)` expands to `(if-let [x y] (do z))`. We can omit the `do`.

**Comment by evg-tso** [comment]
> > Can you elaborate on keeping `if-let` without an `else` branch?
> 
> `(when-let [x y] z)` expands to `(if-let [x y] (do z))`. We can omit the `do`.

So we can remove the `do` from [here](https://github.com/weavejester/integrant/pull/91/files#diff-6debdd49fbcfa133cc20424c16234687a6b1853cc885066f95167744ae240cafL192) as well, right?

**Comment by weavejester** [comment]
> So we can remove the `do` from [here](https://github.com/weavejester/integrant/pull/91/files#diff-6debdd49fbcfa133cc20424c16234687a6b1853cc885066f95167744ae240cafL192) as well, right?

No, in that case I think it aids readability. It forces the reader to notice that the return value is different.

I admit somewhat divided on whether or not `when-let` or `if-let` is better for single-case conditionals, but since it isn't doing any harm, better to keep it how it is.

As I said in my first comment: can you keep the spelling correction, and remove everything else?

**Comment by evg-tso** [comment]
Alright.  
I've squashed and reworded the commit message.  
Should I keep the PR name as it?

**Comment by weavejester** [comment]
I can always change the name of the PR. This should be fine.

**Comment by weavejester** [comment]
Ah, but can you change the commit message to:

    Fix typos in test namespace

**Comment by evg-tso** [comment]
Done.

**Pull request merged**
