### PR TITLE
Precise usage of `ig/read-string`

### PR DESCRIPTION
**Pull request by DjebbZ**
I've been bitten by this right now...

### CODE REVIEW

**Comment by weavejester** [comment]
This change would make the line inconsistant with the rest of the README, which doesn't include the namespace in paragraphs about other functions and methods.

I suggest instead changing it to:

> And load it with Integrant's version of `read-string`:

**Comment by DjebbZ** [comment]
As you wish, sir. Done.

**Comment by weavejester** [comment]
Thanks, can you squash your commits and change the commit message to:

    Make read-string explanation in README clearer

If you don't have time, I'll see to it later.

**Comment by DjebbZ** [comment]
Will do today

**Comment by DjebbZ** [comment]
Here you go.

**Pull request merged**
