### PR TITLE
Add the refmap construct

### LINKED ISSUE #63: RefMap or resolve as protocol method
`RefMap` would be like `RefSet` but would resolve to a map `{k -> ref}` instead a refs set. Knowing the key can be useful (think handler registration).
Alternatively, extend the `RefLike` protocol with a `resolve` method and in `expand-key` postwalk the config via it, this would allow custom `RefThing`s. Sample:

```clojure
(defprotocol RefLike
  (ref-key [r] "Return the key of the reference.")
  (resolve [r config]))
;; ...
(defn- expand-key [config value]
  (walk/postwalk
   #(cond
      (reflike? %) (resolve % config)
      :else %)
   value))
```

### PR DESCRIPTION
**Pull request by clyfe**
The refmap construct is similar to refset, but resolves to a map from
keys to resolved refs, rather than a set of refs; it is useful when the
keys are meaningful to the logic beyond just being a slot in the config
map, and are required in further logic.

Resolves #63

### CODE REVIEW

**Comment by weavejester** [comment]
Please ensure the code and commit message adheres to the contributing guidelines.

**Comment by weavejester** [comment]
Thanks. Can you separate out the introduction of the additional protocol method into its own PR? I'm not sure about `#ig/refmap`, but I'm more willing to accept an extra protocol method to allow that functionality to be added by users. I think I'd also want to call the extra method `ref-resolve` rather than `resolve-ref`.

**Comment by clyfe** [comment]
Rebased on feature/65-reflike-resolve

**Comment by clyfe** [comment]
@weavejester Can you approve or reject this one? Or are you still uncertain?

**Comment by weavejester** [comment]
My thought is that this might be a little too specialized. I'll add the `ref-resolve` method to the next alpha so this functionality can be added manually, but I don't currently think it should be default behaviour. However, I'll keep this in mind as a possible future addition.

**Comment by clyfe** [comment]
Standalone implementation here: https://github.com/tape-framework/refmap

**Pull request closed without merging**
